global_frame: odom
robot_base_frame: /base_footprint
map_type: costmap
plugins:
  - {name: obstacles, type: "costmap_2d::ObstacleLayer"}

update_frequency: 10.0
publish_frequency: 5.0
static_map: false
rolling_window: true
width: 20.0
height: 20.0
resolution: 0.025
origin_x: -10.0
origin_y: -10.0
origin_z: 0.0

transform_tolerance: 0.1
obstacle_range: 5.0
raytrace_range: 10.0
inflation_radius: 0.38
robot_radius: 0.20
footprint_padding: 0.01

obstacles:
  observation_sources: scan
  scan: {topic: scan, data_type: LaserScan, expected_update_rate: 0.3, obstacle_range: 5.5, raytrace_range: 10.0, observation_persistence: 0, marking: true, clearing: true, min_obstacle_height: 0.25, max_obstacle_height: 0.35}

  track_unknown_space: false
  global_frame: odom
  robot_base_frame: /base_footprint
